services:
  - type: web
    name: yj-solapi-node
    env: node
    buildCommand: npm install
    startCommand: node routes/server.js
    envVars:
      - key: PORT
        value: 8080
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
      - key: SOLAPI_PFID
        sync: false
      - key: SOLAPI_TEMPLATE_ID
        sync: false
      - key: SOLAPI_PHONE
        sync: false
